package com.godavari.appsnest.fms.core.utility;

public interface ActionPerformedSuccessFailCode {
    int RESULT_TYPE_SUCCESS = 0;
    int RESULT_TYPE_FAIL = 1;

    int SUCCESS_CODE_INSERT_HEAD_OF_DEPARTMENT= 100;
    int SUCCESS_CODE_INSERT_HOD_MANAGE=101;
    int SUCCESS_CODE_INSERT_VEHICLE_TYPE=102;
    int SUCCESS_CODE_INSERT_VEHICLE_ASSIGNED=103;
    int SUCCESS_CODE_INSERT_ACCOUNT = 104;

    int SUCCESS_CODE_DELETE_HEAD_OF_DEPARTMENT = 200;
    int SUCCESS_CODE_DELETE_HOD_MANAGE = 201;
    int SUCCESS_CODE_DELETE_VEHICLE_TYPE =202;
    int SUCCESS_CODE_DELETE_VEHICLE_ASSIGNED =203;
    int SUCCESS_CODE_DELETE_ACCOUNT =204;

    int SUCCESS_CODE_UPDATE_HEAD_OF_DEPARTMENT = 300;
    int SUCCESS_CODE_UPDATE_HOD_MANAGE = 301;
    int SUCCESS_CODE_UPDATE_VEHICLE_TYPE=302;
    int SUCCESS_CODE_UPDATE_VEHICLE_ASSIGNED=303;
    int SUCCESS_CODE_UPDATE_ACCOUNT = 304;

    int FAIL_CODE_EXCEPTION_THROWN = 9998;
    int FAIL_CODE_SQL_EXCEPTION_THROWN = 9999;


    int FAIL_CODE_INSERT_HEAD_OF_DEPARTMENT_INPUT_ISSUE = 1000;
    int FAIL_CODE_INSERT_HOD_MANAGE_INPUT_ISSUE = 1001;
    int FAIL_CODE_INSERT_VEHICLE_TYPE_INPUT_ISSUE = 1002;
    int FAIL_CODE_INSERT_VEHICLE_ASSIGNED_INPUT_ISSUE = 1003;
    int FAIL_CODE_INSERT_ACCOUNT_INPUT_ISSUE = 1004;

    int FAIL_CODE_DELETE_HEAD_OF_DEPARTMENT_ISSUE = 1100;
    int FAIL_CODE_DELETE_HOD_MANAGE_ISSUE=1101;
    int FAIL_CODE_DELETE_VEHICLE_TYPE_ISSUE=1102;
    int FAIL_CODE_DELETE_VEHICLE_ASSIGNED_ISSUE=1103;
    int FAIL_CODE_DELETE_ACCOUNT_ISSUE=1104;

    int FAIL_CODE_UPDATE_HEAD_OF_DEPARTMENT_INPUT_ISSUE = 1200;
    int FAIL_CODE_UPDATE_HOD_MANAGE_INPUT_ISSUE = 1201;
    int FAIL_CODE_UPDATE_VEHICLE_TYPE_INPUT_ISSUE = 1202;
    int FAIL_CODE_UPDATE_VEHICLE_ASSIGNED_INPUT_ISSUE = 1203;
    int FAIL_CODE_UPDATE_ACCOUNT_INPUT_ISSUE = 1204;

    int FAIL_CODE_BASE_REPORT_INPUT_ISSUE = 1499;
    int SUCCESS_CODE_REPORT_FROM_TO = 1500;
    int FAIL_CODE_REPORT_FROM_TO_INPUT_ISSUE= 1501;
    int SUCCESS_CODE_REPORT_MASTER = 1502;
    int FAIL_CODE_REPORT_MASTER_INPUT_ISSUE = 1503;
    int SUCCESS_CODE_REPORT_MASTER1=1504;
    int FAIL_CODE_REPORT_MASTER1_INPUT_ISSUE = 1505;
    int SUCCESS_CODE_REPORT_VEHICLES=1505;
    int FAIL_CODE_REPORT_VEHICLES_INPUT_ISSUE = 1506;
    int SUCCESS_CODE_REPORT_DEPARTMENTS=1507;
    int FAIL_CODE_REPORT_DEPARTMENTS_INPUT_ISSUE = 1508;

    int SUCCESS_CODE_START_SCREEN_USER_GENERATED_AND_SAVED_PASSWORD_MATCHED = 10000;
    int SUCCESS_CODE_START_SCREEN_ADMIN_AND_USER_SAVED_PASSWORD_MATCHED = 10001;
    int FAIL_CODE_ADMIN_FILE_NOT_FOUND = 10003;
    int FAIL_CODE_USER_FILE_SAVED_NOT_FOUND = 10004;
    int FAIL_CODE_USER_FILE_GENERATED_NOT_FOUND = 10005;
    int FAIL_CODE_ADMIN_USER_GENERATED_AND_SAVED_SECURE_PASSWORD_NOT_MATCH = 10006;

    int SUCCESS_CODE_ACTIVATION_USER_SECURE_PASSWORD_MATCHED = 600;
    int SUCCESS_CODE_ACTIVATION_ADMIN_SECURE_PASSWORD_MATCHED = 601;
    int FAIL_CODE_ACTIVATION_USER_PASSWORD_KEY_EMPTY = 602;
    int FAIL_CODE_ACTIVATION_USER_SALE_KEY_EMPTY = 603;
    //int FAIL_CODE_ACTIVATION_USER_SECURE_PASSWORD_DOESNT_MATCH = 604;
    int FAIL_CODE_ACTIVATION_USER_INPUT_ISSUE = 650;

    int FAIL_CODE_LOGIN_SCREEN_INPUT_ISSUE=700;
    int FAIL_CODE_LOGIN_USERNAME_PASSWORD_NOT_MATCHED =701;
    int SUCCESS_CODE_LOGIN_DEVELOPER_USERNAME_PASSWORD_MATCHED = 702;
    int SUCCESS_CODE_LOGIN_ADMIN_TYPE_USERNAME_PASSWORD_MATCHED =703;
    int SUCCESS_CODE_LOGIN_USER_TYPE_USERNAME_PASSWORD_MATCHED =704;


}
